/* GENERATED by tools/vpy_to_music.py from docs/VX-COOP/music_example.vpy - DO NOT HAND-EDIT.
 * Copyright (C) 2026 Caelotronics.
 * Regenerate: python3 tools/vpy_to_music.py docs/VX-COOP/music_example.vpy code/stm32/vxcoop/vxcoop_music_example.c code/stm32/vxcoop/vxcoop_music_example.h example vxc
 */
#ifndef VXC_MUSIC_EXAMPLE_H
#define VXC_MUSIC_EXAMPLE_H

#include "../vxt/vxt_music.h"

extern const VxtMusicSong vxcMusic_example;

#endif /* VXC_MUSIC_EXAMPLE_H */
