{
  "version": "1.0",
  "name": "Imported MIDI",
  "author": "",
  "tempo": 120,
  "ticksPerBeat": 24,
  "totalTicks": 1642,
  "notes": [
    {
      "id": "krl9ujhx2",
      "note": 81,
      "start": 0,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "mjzo7zjdr",
      "note": 65,
      "start": 0,
      "duration": 6,
      "velocity": 14,
      "channel": 1
    },
    {
      "id": "en5x1jo5d",
      "note": 38,
      "start": 0,
      "duration": 12,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "qaxv9dcth",
      "note": 86,
      "start": 12,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "8m9wivbce",
      "note": 69,
      "start": 12,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "iv42vnvme",
      "note": 81,
      "start": 24,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "ka452ak9d",
      "note": 65,
      "start": 24,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "38hm2r6o4",
      "note": 45,
      "start": 24,
      "duration": 12,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "p0umn414w",
      "note": 86,
      "start": 36,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "0zau4ip3a",
      "note": 69,
      "start": 36,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "o30zkwna2",
      "note": 81,
      "start": 48,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "vae9z5b6m",
      "note": 65,
      "start": 48,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "aob57e2nd",
      "note": 38,
      "start": 48,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "v8jlmyiix",
      "note": 86,
      "start": 54,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "e6w3kmvt4",
      "note": 69,
      "start": 54,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "gqcru6whp",
      "note": 81,
      "start": 66,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "hjsde0fzm",
      "note": 65,
      "start": 66,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "7jvlv0cow",
      "note": 45,
      "start": 72,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "8soi70l6z",
      "note": 80,
      "start": 78,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "l5ogah7pj",
      "note": 64,
      "start": 78,
      "duration": 3,
      "velocity": 10,
      "channel": 2
    },
    {
      "id": "tgfqkdl7a",
      "note": 81,
      "start": 84,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "w87xgbt8v",
      "note": 65,
      "start": 84,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "6fz53thmd",
      "note": 81,
      "start": 96,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "nw9tczlip",
      "note": 69,
      "start": 96,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "ir18bftin",
      "note": 38,
      "start": 96,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "cc888jzdg",
      "note": 80,
      "start": 102,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "qbupsbi4x",
      "note": 68,
      "start": 102,
      "duration": 3,
      "velocity": 9,
      "channel": 1
    },
    {
      "id": "czkl01eg3",
      "note": 81,
      "start": 108,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "w634t7sdn",
      "note": 69,
      "start": 108,
      "duration": 6,
      "velocity": 8,
      "channel": 1
    },
    {
      "id": "70ylo1k5g",
      "note": 79,
      "start": 114,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "1xjdtcv0f",
      "note": 67,
      "start": 114,
      "duration": 6,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "btpurklbu",
      "note": 36,
      "start": 120,
      "duration": 12,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "d14hc43iq",
      "note": 78,
      "start": 126,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "ly6dxvfei",
      "note": 66,
      "start": 126,
      "duration": 3,
      "velocity": 10,
      "channel": 2
    },
    {
      "id": "s4ya9nc39",
      "note": 79,
      "start": 132,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "v3yzlo4yg",
      "note": 67,
      "start": 132,
      "duration": 6,
      "velocity": 7,
      "channel": 1
    },
    {
      "id": "7kxa60kq9",
      "note": 78,
      "start": 138,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "w6593r25d",
      "note": 66,
      "start": 138,
      "duration": 6,
      "velocity": 9,
      "channel": 1
    },
    {
      "id": "87hap275y",
      "note": 77,
      "start": 144,
      "duration": 18,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "4vhjwu8g2",
      "note": 65,
      "start": 144,
      "duration": 9,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "8d0jtw513",
      "note": 41,
      "start": 144,
      "duration": 24,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "ntgyq7oap",
      "note": 74,
      "start": 162,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "0vyz8zluo",
      "note": 62,
      "start": 162,
      "duration": 3,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "3ckj6oh5t",
      "note": 48,
      "start": 168,
      "duration": 12,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "uz915kget",
      "note": 81,
      "start": 192,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "fg6n2zvdz",
      "note": 65,
      "start": 192,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "3svyuswqi",
      "note": 38,
      "start": 192,
      "duration": 12,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "nu91pdee1",
      "note": 86,
      "start": 204,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "t363dgy7n",
      "note": 64,
      "start": 204,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "7nbjb2493",
      "note": 81,
      "start": 216,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "buvzqalbe",
      "note": 65,
      "start": 216,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "iujy8ncl3",
      "note": 45,
      "start": 216,
      "duration": 12,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "ertkq3ma5",
      "note": 86,
      "start": 228,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "tv9qedwya",
      "note": 64,
      "start": 228,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "4ds9ys9vo",
      "note": 81,
      "start": 240,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "5kx3h35tx",
      "note": 65,
      "start": 240,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "p52toqbxv",
      "note": 38,
      "start": 240,
      "duration": 12,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "27r8wj9fi",
      "note": 86,
      "start": 246,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "mub7f4oud",
      "note": 64,
      "start": 246,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "u9m0etlqc",
      "note": 81,
      "start": 258,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "s0fa6k1cf",
      "note": 65,
      "start": 258,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "vunb9yolf",
      "note": 45,
      "start": 264,
      "duration": 12,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "m2q07oing",
      "note": 80,
      "start": 270,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "d69827e24",
      "note": 64,
      "start": 270,
      "duration": 3,
      "velocity": 10,
      "channel": 2
    },
    {
      "id": "7eucuee4d",
      "note": 81,
      "start": 276,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "j3o9s27sm",
      "note": 65,
      "start": 276,
      "duration": 6,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "8keqx8lcd",
      "note": 79,
      "start": 288,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "awghuynxu",
      "note": 67,
      "start": 288,
      "duration": 6,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "0ats4736r",
      "note": 43,
      "start": 288,
      "duration": 12,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "008bllt4p",
      "note": 79,
      "start": 300,
      "duration": 16,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "hnh1sf9sb",
      "note": 67,
      "start": 300,
      "duration": 18,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "z1zrlfqtm",
      "note": 43,
      "start": 312,
      "duration": 12,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "ez9en12nr",
      "note": 78,
      "start": 316,
      "duration": 4,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "81i1wm7e8",
      "note": 66,
      "start": 318,
      "duration": 6,
      "velocity": 9,
      "channel": 1
    },
    {
      "id": "1jaconxqw",
      "note": 79,
      "start": 321,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "dmzby2q7l",
      "note": 67,
      "start": 324,
      "duration": 6,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "qdp3k9pqa",
      "note": 84,
      "start": 336,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "rtdprr807",
      "note": 72,
      "start": 336,
      "duration": 6,
      "velocity": 7,
      "channel": 1
    },
    {
      "id": "9jf48g7fy",
      "note": 36,
      "start": 336,
      "duration": 6,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "1if397owl",
      "note": 82,
      "start": 342,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "oo0f0etle",
      "note": 70,
      "start": 342,
      "duration": 12,
      "velocity": 7,
      "channel": 1
    },
    {
      "id": "87twy6bqp",
      "note": 38,
      "start": 348,
      "duration": 6,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "6opx7o6iq",
      "note": 81,
      "start": 354,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "1d4df9zbn",
      "note": 69,
      "start": 354,
      "duration": 12,
      "velocity": 9,
      "channel": 1
    },
    {
      "id": "9e5odg5mr",
      "note": 39,
      "start": 360,
      "duration": 6,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "m703hqgjz",
      "note": 79,
      "start": 366,
      "duration": 9,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "aeam8h6di",
      "note": 67,
      "start": 366,
      "duration": 9,
      "velocity": 8,
      "channel": 1
    },
    {
      "id": "hoxacdbs8",
      "note": 40,
      "start": 372,
      "duration": 6,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "4sp89bqwd",
      "note": 81,
      "start": 384,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "zhnwix72i",
      "note": 65,
      "start": 384,
      "duration": 6,
      "velocity": 15,
      "channel": 1
    },
    {
      "id": "wd8uilt3e",
      "note": 38,
      "start": 384,
      "duration": 12,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "ff81voav5",
      "note": 86,
      "start": 396,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "652fv6ltf",
      "note": 69,
      "start": 396,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "9kx4zce97",
      "note": 81,
      "start": 408,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "wcalsgn8p",
      "note": 65,
      "start": 408,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "qt8yr8ez1",
      "note": 45,
      "start": 408,
      "duration": 12,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "fz6veml3s",
      "note": 86,
      "start": 420,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "726tcq08x",
      "note": 69,
      "start": 420,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "t1u5n2pxh",
      "note": 81,
      "start": 432,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "feijv40d0",
      "note": 65,
      "start": 432,
      "duration": 6,
      "velocity": 14,
      "channel": 1
    },
    {
      "id": "h7o8kauku",
      "note": 38,
      "start": 432,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "he5hckh29",
      "note": 86,
      "start": 438,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "9cwlilvbx",
      "note": 69,
      "start": 438,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "ajslug4sy",
      "note": 81,
      "start": 450,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "yfhksjwul",
      "note": 65,
      "start": 450,
      "duration": 6,
      "velocity": 14,
      "channel": 1
    },
    {
      "id": "6xw0kxwh3",
      "note": 45,
      "start": 456,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "buoreyl9p",
      "note": 80,
      "start": 462,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "7jfw8isxt",
      "note": 64,
      "start": 462,
      "duration": 6,
      "velocity": 11,
      "channel": 2
    },
    {
      "id": "exwb9ox1o",
      "note": 81,
      "start": 468,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "z3ll0wi99",
      "note": 65,
      "start": 468,
      "duration": 6,
      "velocity": 15,
      "channel": 1
    },
    {
      "id": "ielgc7v0z",
      "note": 84,
      "start": 480,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "wpqy9idwf",
      "note": 72,
      "start": 480,
      "duration": 6,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "y7d28kd7w",
      "note": 36,
      "start": 480,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "xjawjh5re",
      "note": 84,
      "start": 492,
      "duration": 18,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "npf7ew9j9",
      "note": 72,
      "start": 492,
      "duration": 12,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "l549wtvlh",
      "note": 36,
      "start": 504,
      "duration": 12,
      "velocity": 14,
      "channel": 1
    },
    {
      "id": "vhw982790",
      "note": 81,
      "start": 510,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "gxgbhsbw8",
      "note": 69,
      "start": 510,
      "duration": 6,
      "velocity": 10,
      "channel": 2
    },
    {
      "id": "to5x9alfm",
      "note": 79,
      "start": 516,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "gx4bxldby",
      "note": 67,
      "start": 516,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "wzu75bkii",
      "note": 77,
      "start": 528,
      "duration": 18,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "c7s6zvvpi",
      "note": 65,
      "start": 528,
      "duration": 18,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "hjnso0y7x",
      "note": 41,
      "start": 528,
      "duration": 24,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "5sv1i3a3q",
      "note": 74,
      "start": 546,
      "duration": 3,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "h7lix6103",
      "note": 62,
      "start": 546,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "4tb8mgdrw",
      "note": 48,
      "start": 552,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "uhzt2jf0o",
      "note": 74,
      "start": 576,
      "duration": 24,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "8hfq7ya7o",
      "note": 53,
      "start": 576,
      "duration": 2,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "1zy2y6wdy",
      "note": 46,
      "start": 576,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "rak7fbk9o",
      "note": 58,
      "start": 578,
      "duration": 12,
      "velocity": 14,
      "channel": 1
    },
    {
      "id": "bp7wmsbob",
      "note": 59,
      "start": 590,
      "duration": 7,
      "velocity": 7,
      "channel": 1
    },
    {
      "id": "3isd1ac7v",
      "note": 61,
      "start": 597,
      "duration": 4,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "94mvs8pta",
      "note": 77,
      "start": 600,
      "duration": 18,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "kxl6auvdq",
      "note": 46,
      "start": 600,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "2n5dfrf1i",
      "note": 62,
      "start": 601,
      "duration": 17,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "p8lb5mnly",
      "note": 80,
      "start": 618,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "qp08ybfyd",
      "note": 63,
      "start": 618,
      "duration": 3,
      "velocity": 8,
      "channel": 1
    },
    {
      "id": "dmp4yc0wm",
      "note": 64,
      "start": 623,
      "duration": 2,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "vc2r57as7",
      "note": 81,
      "start": 624,
      "duration": 24,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "woxl0ulpl",
      "note": 41,
      "start": 624,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "zh5fltrtg",
      "note": 65,
      "start": 625,
      "duration": 23,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "g9vpa1v1a",
      "note": 67,
      "start": 644,
      "duration": 1,
      "velocity": 6,
      "channel": 2
    },
    {
      "id": "48witf0rs",
      "note": 68,
      "start": 645,
      "duration": 3,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "9d20iras1",
      "note": 84,
      "start": 648,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "g4rhr6810",
      "note": 69,
      "start": 648,
      "duration": 12,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "6oxklp6dz",
      "note": 38,
      "start": 648,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "664rznp6d",
      "note": 87,
      "start": 672,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "ka8qj5wfy",
      "note": 75,
      "start": 672,
      "duration": 6,
      "velocity": 15,
      "channel": 1
    },
    {
      "id": "wgcia21df",
      "note": 43,
      "start": 672,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "o48ji0445",
      "note": 86,
      "start": 684,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "cdn1mdggk",
      "note": 74,
      "start": 684,
      "duration": 6,
      "velocity": 15,
      "channel": 1
    },
    {
      "id": "dv6mdukxs",
      "note": 80,
      "start": 696,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "czerwnztq",
      "note": 68,
      "start": 696,
      "duration": 3,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "e3w6o9eh9",
      "note": 36,
      "start": 696,
      "duration": 24,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "9scjc2wcu",
      "note": 81,
      "start": 702,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "awmisodxm",
      "note": 69,
      "start": 702,
      "duration": 6,
      "velocity": 14,
      "channel": 1
    },
    {
      "id": "0gs1j9hjl",
      "note": 77,
      "start": 714,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "4ys7m9vvm",
      "note": 65,
      "start": 714,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "4pzk2rx3x",
      "note": 41,
      "start": 720,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "z6il3i2wx",
      "note": 40,
      "start": 732,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "ws1wk13dk",
      "note": 38,
      "start": 744,
      "duration": 6,
      "velocity": 10,
      "channel": 0
    },
    {
      "id": "bschqb3lh",
      "note": 36,
      "start": 756,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "usr1dam24",
      "note": 38,
      "start": 768,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "lqi8fceat",
      "note": 81,
      "start": 774,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "jr4l1aj0a",
      "note": 74,
      "start": 774,
      "duration": 3,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "vdmzkytdj",
      "note": 69,
      "start": 780,
      "duration": 3,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "kchuv2uzw",
      "note": 77,
      "start": 786,
      "duration": 3,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "nnym488iz",
      "note": 69,
      "start": 786,
      "duration": 3,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "j2bkrjsst",
      "note": 81,
      "start": 792,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "vdyup0cux",
      "note": 74,
      "start": 792,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "9jo6ry227",
      "note": 45,
      "start": 792,
      "duration": 12,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "qnyyuczlp",
      "note": 69,
      "start": 804,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "ngawlzqdk",
      "note": 38,
      "start": 816,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "lxw0am4d3",
      "note": 81,
      "start": 822,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "o3s5cy8ky",
      "note": 74,
      "start": 822,
      "duration": 6,
      "velocity": 10,
      "channel": 2
    },
    {
      "id": "hic31edp3",
      "note": 69,
      "start": 828,
      "duration": 3,
      "velocity": 10,
      "channel": 0
    },
    {
      "id": "6oadmp2i7",
      "note": 77,
      "start": 834,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "pkfteu58r",
      "note": 69,
      "start": 834,
      "duration": 3,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "74qlew1kx",
      "note": 81,
      "start": 840,
      "duration": 12,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "3o4w9pxbr",
      "note": 74,
      "start": 840,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "8v52wzbbo",
      "note": 45,
      "start": 840,
      "duration": 24,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "daju0aetz",
      "note": 69,
      "start": 852,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "yzl53e3bx",
      "note": 38,
      "start": 864,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "zg1dowuce",
      "note": 81,
      "start": 870,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "5vnq0tyzx",
      "note": 74,
      "start": 870,
      "duration": 3,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "s47xel76z",
      "note": 69,
      "start": 876,
      "duration": 3,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "6dh7l54lo",
      "note": 77,
      "start": 882,
      "duration": 3,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "2e3en622z",
      "note": 69,
      "start": 882,
      "duration": 3,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "vqtza8poc",
      "note": 80,
      "start": 888,
      "duration": 6,
      "velocity": 10,
      "channel": 0
    },
    {
      "id": "i3uo49f1b",
      "note": 74,
      "start": 888,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "8gauh8jon",
      "note": 45,
      "start": 888,
      "duration": 12,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "93eeyu6xw",
      "note": 81,
      "start": 894,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "uwepkif77",
      "note": 73,
      "start": 894,
      "duration": 3,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "2rv7oo3x6",
      "note": 69,
      "start": 900,
      "duration": 3,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "sfxbwin2h",
      "note": 77,
      "start": 906,
      "duration": 24,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "rme6cud6h",
      "note": 69,
      "start": 906,
      "duration": 18,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "tlfwk40wr",
      "note": 38,
      "start": 912,
      "duration": 9,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "w6421ajvx",
      "note": 69,
      "start": 924,
      "duration": 3,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "j5wg7444i",
      "note": 74,
      "start": 930,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "cq3ag4sra",
      "note": 65,
      "start": 930,
      "duration": 12,
      "velocity": 9,
      "channel": 1
    },
    {
      "id": "9ilbw2njy",
      "note": 44,
      "start": 930,
      "duration": 18,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "5sejv9qqe",
      "note": 69,
      "start": 948,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "e2r45agwd",
      "note": 45,
      "start": 948,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "gu6epoj3e",
      "note": 38,
      "start": 960,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "2wcfxi2ci",
      "note": 81,
      "start": 966,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "gd7ualsc0",
      "note": 74,
      "start": 966,
      "duration": 3,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "3mlizrjm2",
      "note": 69,
      "start": 972,
      "duration": 3,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "gcsxow2ms",
      "note": 77,
      "start": 978,
      "duration": 3,
      "velocity": 9,
      "channel": 0
    },
    {
      "id": "q951i802q",
      "note": 69,
      "start": 978,
      "duration": 3,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "071xvfjfo",
      "note": 81,
      "start": 984,
      "duration": 12,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "f6mql8554",
      "note": 74,
      "start": 984,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "63w9vp4bp",
      "note": 45,
      "start": 984,
      "duration": 12,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "0s1qupv23",
      "note": 69,
      "start": 996,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "g7re68cqg",
      "note": 38,
      "start": 1008,
      "duration": 12,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "5fatxtq4x",
      "note": 81,
      "start": 1014,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "z5kzvfyqg",
      "note": 74,
      "start": 1014,
      "duration": 3,
      "velocity": 11,
      "channel": 2
    },
    {
      "id": "rbsm2agr0",
      "note": 69,
      "start": 1020,
      "duration": 3,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "926uwcmha",
      "note": 77,
      "start": 1026,
      "duration": 3,
      "velocity": 7,
      "channel": 0
    },
    {
      "id": "4zc2v67kb",
      "note": 69,
      "start": 1026,
      "duration": 3,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "esiaznyyu",
      "note": 81,
      "start": 1032,
      "duration": 12,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "wuot3jdp6",
      "note": 74,
      "start": 1032,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "0rdo4jobt",
      "note": 45,
      "start": 1032,
      "duration": 24,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "63qacayi1",
      "note": 69,
      "start": 1044,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "nkj4tvs1e",
      "note": 38,
      "start": 1056,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "515vjqm2q",
      "note": 81,
      "start": 1062,
      "duration": 6,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "e9vi4efk8",
      "note": 74,
      "start": 1062,
      "duration": 6,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "sam5g8jgq",
      "note": 69,
      "start": 1068,
      "duration": 3,
      "velocity": 10,
      "channel": 0
    },
    {
      "id": "0ddvauvra",
      "note": 77,
      "start": 1074,
      "duration": 6,
      "velocity": 8,
      "channel": 0
    },
    {
      "id": "5g1gxz432",
      "note": 69,
      "start": 1074,
      "duration": 3,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "ei23cy05o",
      "note": 80,
      "start": 1080,
      "duration": 6,
      "velocity": 8,
      "channel": 0
    },
    {
      "id": "crx5i17q0",
      "note": 74,
      "start": 1080,
      "duration": 3,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "msqbesaw1",
      "note": 45,
      "start": 1080,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "4iwupbm5w",
      "note": 81,
      "start": 1086,
      "duration": 6,
      "velocity": 9,
      "channel": 0
    },
    {
      "id": "2r2vxwznm",
      "note": 74,
      "start": 1086,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "sjw5p0uth",
      "note": 69,
      "start": 1092,
      "duration": 4,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "eyjijij8p",
      "note": 79,
      "start": 1098,
      "duration": 24,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "hr8rz3uhq",
      "note": 73,
      "start": 1098,
      "duration": 24,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "6wsc1fwek",
      "note": 39,
      "start": 1104,
      "duration": 24,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "o8lohlo3w",
      "note": 63,
      "start": 1122,
      "duration": 2,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "norhjsykk",
      "note": 64,
      "start": 1124,
      "duration": 28,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "ugtu1d8ke",
      "note": 77,
      "start": 1126,
      "duration": 1,
      "velocity": 8,
      "channel": 1
    },
    {
      "id": "wghs4ytnj",
      "note": 74,
      "start": 1127,
      "duration": 25,
      "velocity": 9,
      "channel": 1
    },
    {
      "id": "8hxt01u94",
      "note": 72,
      "start": 1128,
      "duration": 12,
      "velocity": 9,
      "channel": 2
    },
    {
      "id": "brsue0l61",
      "note": 72,
      "start": 1140,
      "duration": 6,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "fogpw6vbk",
      "note": 38,
      "start": 1152,
      "duration": 12,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "b1hiwnjnu",
      "note": 81,
      "start": 1158,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "snrrr3avz",
      "note": 74,
      "start": 1158,
      "duration": 3,
      "velocity": 11,
      "channel": 2
    },
    {
      "id": "odf5zdvyf",
      "note": 69,
      "start": 1164,
      "duration": 3,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "pw8oggn28",
      "note": 77,
      "start": 1170,
      "duration": 6,
      "velocity": 9,
      "channel": 0
    },
    {
      "id": "aru2dodjk",
      "note": 69,
      "start": 1170,
      "duration": 3,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "2xlwy2trh",
      "note": 81,
      "start": 1176,
      "duration": 12,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "1km40pn11",
      "note": 74,
      "start": 1176,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "ksytp2bpu",
      "note": 45,
      "start": 1176,
      "duration": 12,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "qxyau6d8t",
      "note": 69,
      "start": 1188,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "i6wimjb3x",
      "note": 38,
      "start": 1200,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "c8kfo81he",
      "note": 81,
      "start": 1206,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "p0oh137y4",
      "note": 74,
      "start": 1206,
      "duration": 3,
      "velocity": 11,
      "channel": 2
    },
    {
      "id": "4akkc2h9j",
      "note": 69,
      "start": 1212,
      "duration": 3,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "weri5dccx",
      "note": 77,
      "start": 1218,
      "duration": 3,
      "velocity": 8,
      "channel": 0
    },
    {
      "id": "pfo54d5n9",
      "note": 69,
      "start": 1218,
      "duration": 3,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "1pn46ejgm",
      "note": 81,
      "start": 1224,
      "duration": 12,
      "velocity": 10,
      "channel": 0
    },
    {
      "id": "i6yv1408u",
      "note": 74,
      "start": 1224,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "9c78zw1kf",
      "note": 45,
      "start": 1224,
      "duration": 24,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "sevss8wem",
      "note": 69,
      "start": 1236,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "2oerg3093",
      "note": 38,
      "start": 1248,
      "duration": 12,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "2jbygm04s",
      "note": 81,
      "start": 1254,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "c6g8yqyji",
      "note": 74,
      "start": 1254,
      "duration": 3,
      "velocity": 11,
      "channel": 2
    },
    {
      "id": "6ltiiegcd",
      "note": 69,
      "start": 1260,
      "duration": 3,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "3k47y5b1o",
      "note": 77,
      "start": 1266,
      "duration": 6,
      "velocity": 7,
      "channel": 0
    },
    {
      "id": "ycgtxkhl",
      "note": 69,
      "start": 1266,
      "duration": 3,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "ax7loyx7n",
      "note": 80,
      "start": 1272,
      "duration": 6,
      "velocity": 10,
      "channel": 0
    },
    {
      "id": "uyyamy1iw",
      "note": 74,
      "start": 1272,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "rt66i910y",
      "note": 45,
      "start": 1272,
      "duration": 12,
      "velocity": 12,
      "channel": 2
    },
    {
      "id": "210zd4d28",
      "note": 81,
      "start": 1278,
      "duration": 6,
      "velocity": 8,
      "channel": 0
    },
    {
      "id": "tyi2i134w",
      "note": 73,
      "start": 1278,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "2sz9rf58z",
      "note": 69,
      "start": 1284,
      "duration": 3,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "wv0rhqiez",
      "note": 77,
      "start": 1290,
      "duration": 24,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "roml1pcb2",
      "note": 69,
      "start": 1290,
      "duration": 18,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "mlwet88vp",
      "note": 38,
      "start": 1296,
      "duration": 24,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "owoy361xk",
      "note": 69,
      "start": 1308,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "l7v5gw76i",
      "note": 74,
      "start": 1314,
      "duration": 12,
      "velocity": 9,
      "channel": 0
    },
    {
      "id": "phx82gu71",
      "note": 65,
      "start": 1314,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "9qw6six1a",
      "note": 45,
      "start": 1320,
      "duration": 12,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "toe74o92k",
      "note": 69,
      "start": 1332,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "trujltdyy",
      "note": 70,
      "start": 1344,
      "duration": 6,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "3lwuil4tc",
      "note": 58,
      "start": 1344,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "9wr96wecb",
      "note": 46,
      "start": 1344,
      "duration": 3,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "0tn2li2v3",
      "note": 74,
      "start": 1350,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "k7e5es0mk",
      "note": 62,
      "start": 1350,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "7ivv3z4hg",
      "note": 46,
      "start": 1350,
      "duration": 9,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "z1it97iid",
      "note": 77,
      "start": 1356,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "245ra0ctw",
      "note": 65,
      "start": 1356,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "d7i76zpa3",
      "note": 71,
      "start": 1368,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "nau1qp8ev",
      "note": 59,
      "start": 1368,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "fj4kepzcc",
      "note": 46,
      "start": 1368,
      "duration": 3,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "c6qm8o2fj",
      "note": 74,
      "start": 1374,
      "duration": 6,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "20itng5oo",
      "note": 62,
      "start": 1374,
      "duration": 6,
      "velocity": 11,
      "channel": 1
    },
    {
      "id": "l29bj1go9",
      "note": 46,
      "start": 1374,
      "duration": 9,
      "velocity": 14,
      "channel": 2
    },
    {
      "id": "8i7gitprx",
      "note": 77,
      "start": 1380,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "n0wa89sf1",
      "note": 65,
      "start": 1380,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "ahtj8jtwd",
      "note": 80,
      "start": 1392,
      "duration": 6,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "kiqls7wvk",
      "note": 68,
      "start": 1392,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "ajr1f9zk5",
      "note": 48,
      "start": 1392,
      "duration": 18,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "3jyklgki7",
      "note": 81,
      "start": 1398,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "xv2pomkc3",
      "note": 69,
      "start": 1398,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "v3mq8kj4d",
      "note": 74,
      "start": 1410,
      "duration": 12,
      "velocity": 11,
      "channel": 0
    },
    {
      "id": "7yu4ozwn8",
      "note": 62,
      "start": 1410,
      "duration": 6,
      "velocity": 10,
      "channel": 1
    },
    {
      "id": "6etk5jpdy",
      "note": 38,
      "start": 1410,
      "duration": 12,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "witft1u7i",
      "note": 38,
      "start": 1428,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "gdsl9mupr",
      "note": 62,
      "start": 1440,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "vvw7ectt3",
      "note": 62,
      "start": 1440,
      "duration": 6,
      "velocity": 13,
      "channel": 1
    },
    {
      "id": "y4r1kui0y",
      "note": 43,
      "start": 1440,
      "duration": 24,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "h6vb3onsk",
      "note": 65,
      "start": 1446,
      "duration": 6,
      "velocity": 10,
      "channel": 0
    },
    {
      "id": "43fgf2e3w",
      "note": 65,
      "start": 1446,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "jnghwa3gd",
      "note": 72,
      "start": 1452,
      "duration": 6,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "wi3pgm06a",
      "note": 70,
      "start": 1452,
      "duration": 6,
      "velocity": 9,
      "channel": 1
    },
    {
      "id": "94hr0336o",
      "note": 74,
      "start": 1458,
      "duration": 6,
      "velocity": 12,
      "channel": 0
    },
    {
      "id": "5qkc1xb7j",
      "note": 62,
      "start": 1458,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "rwrru7m4z",
      "note": 68,
      "start": 1464,
      "duration": 6,
      "velocity": 13,
      "channel": 0
    },
    {
      "id": "k2mn5udqh",
      "note": 68,
      "start": 1464,
      "duration": 6,
      "velocity": 12,
      "channel": 1
    },
    {
      "id": "p5z22zqtt",
      "note": 36,
      "start": 1464,
      "duration": 18,
      "velocity": 13,
      "channel": 2
    },
    {
      "id": "slc6t17n4",
      "note": 69,
      "start": 1470,
      "duration": 6,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "taszkkqcx",
      "note": 69,
      "start": 1470,
      "duration": 6,
      "velocity": 15,
      "channel": 1
    },
    {
      "id": "1vgn11gc3",
      "note": 65,
      "start": 1482,
      "duration": 6,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "mmzddqgpy",
      "note": 65,
      "start": 1482,
      "duration": 6,
      "velocity": 15,
      "channel": 1
    },
    {
      "id": "j38u76gir",
      "note": 41,
      "start": 1482,
      "duration": 12,
      "velocity": 15,
      "channel": 2
    },
    {
      "id": "h6z9nik1k",
      "note": 40,
      "start": 1500,
      "duration": 6,
      "velocity": 15,
      "channel": 0
    },
    {
      "id": "c0ivrjv4f",
      "note": 38,
      "start": 1512,
      "duration": 6,
      "velocity": 14,
      "channel": 0
    },
    {
      "id": "orizw8urk",
      "note": 36,
      "start": 1524,
      "duration": 6,
      "velocity": 15,
      "channel": 0
    }
  ],
  "noise": [],
  "loopStart": 0,
  "loopEnd": 1642,
  "channel_instruments": {}
}